// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2m7J47b1xeCF3Fss3X6AqQLXxEkfRsRU',
    appId: '1:1074077598781:android:f77ed35bb2bab1ee321654',
    messagingSenderId: '1074077598781',
    projectId: 'harmoniaauth',
    storageBucket: 'harmoniaauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdNaiCV3mHbA4REJX9wZnwo_XV9MqWlN0',
    appId: '1:1074077598781:ios:8e9c40af5603cdc7321654',
    messagingSenderId: '1074077598781',
    projectId: 'harmoniaauth',
    storageBucket: 'harmoniaauth.firebasestorage.app',
    iosClientId: '1074077598781-qj9b1lluejsd0sst9ntsh8hf2hbqe358.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdNaiCV3mHbA4REJX9wZnwo_XV9MqWlN0',
    appId: '1:1074077598781:ios:8e9c40af5603cdc7321654',
    messagingSenderId: '1074077598781',
    projectId: 'harmoniaauth',
    storageBucket: 'harmoniaauth.firebasestorage.app',
    iosClientId: '1074077598781-qj9b1lluejsd0sst9ntsh8hf2hbqe358.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy9LuOHsNf4u831nq4rbzSP_dSeMqzQ-8',
    appId: '1:1074077598781:web:a8fd920f3a0ee23d321654',
    messagingSenderId: '1074077598781',
    projectId: 'harmoniaauth',
    authDomain: 'harmoniaauth.firebaseapp.com',
    storageBucket: 'harmoniaauth.firebasestorage.app',
  );

}